### PR TITLE
feat(persistent_sessions): don't use rocksdb when unavailable

### PR DESCRIPTION
**Pull request by thalesmg**

### CODE REVIEW

**Review by ieQu1 — APPROVED** [review]

**Comment by thalesmg** [comment]
Had to rebase because of a conflict in `CHANGES-v5.0.md`.

**Comment by thalesmg** [comment]
Mix build is failing because of this: https://github.com/elixir-lang/elixir/issues/12000

**Review by ieQu1 — APPROVED** [review]

**Review by zmstone — APPROVED** [review]

**Comment by zmstone** [comment]
hmm conflicts.

**Comment by thalesmg** [comment]
@zmstone @ieQu1 Yet another changelog conflict :see_no_evil: 

Should be resolved for the next few minutes at least :crossed_fingers:

**Comment by thalesmg** [comment]
Can't believe I hit another digit-only-starting-with-zero git hash... :see_no_evil: 

https://github.com/emqx/emqx/runs/7467994847?check_suite_focus=true#step:6:12196

**Review by ieQu1 — APPROVED** [review]

**Pull request merged**
