### PR TITLE
ci: check if given schema.json exists before running spellcheck

### PR DESCRIPTION
**Pull request by thalesmg**
Prints helpful message when schema.json does not exist, as otherwise the "file" will be mounted as an empty directory inside the spellchecker container.

### <samp>🤖 Generated by Copilot at 41350b6</samp>

Improve spellcheck script and documentation. Add a check for `schema` file in `spellcheck.sh` and fix some typos.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Review by paulozulato — APPROVED** [review]
Good point!

**Comment by thalesmg** [comment]
The `check_apps_version` failure seems to be a false positive: the changes here do not affect those apps; it's probably due to v5.0.24 being released recently, so it's safe to ignore.

**Comment by lafirest** [comment]
> The `check_apps_version` failure seems to be a false positive: the changes here do not affect those apps; it's probably due to v5.0.24 being released recently, so it's safe to ignore.

I had fixed them, you can just ignore

**Review by zmstone — APPROVED** [review]

**Comment by thalesmg** [comment]
It seems like GH CI won't let this be merged due to the apps version check, so I'll have to rebase this... :facepalm:

**Pull request merged**
