### PR TITLE
feat: clear monitor data using the HTTP API

### PR DESCRIPTION
**Pull request by zhongwencool**
Feature: https://github.com/emqx/emqx/issues/10246

Need dashboard support delete /monitor API 

Release version: v/e5.8.4

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [x] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Comment by zmstone** [comment]
@zhongwencool thank you for the PR, could you rebase to the branch `release-584`?

**Comment by zhongwencool** [comment]
> @zhongwencool thank you for the PR, could you rebase to the branch `release-584`?

DONE.

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-5336)

**Comment by AndriyKhymera** [comment]
Hey @zhongwencool 
I can see that you've merged the changes and they are part of the 5.8.4 release. But for some reason, this doesn't work for me.

I'm doing:
1. DELETE on ../api/v5/metrics. Getting 204.
2. GET ../api/v5/metrics. Getting 200 with list of metrics. Same on dashboard ../dashboard/metrics/


I'm using the emqx:latest docker image and I can't get the metrics cleaned up. From the docker inspect I can see that image was created at "2025-01-07T05:32:24Z". 

All the metrics should be cleaned up if I use the endpoint. For example "messages.publish" or "messages.dropped", right?
Is there some config or known issues where this might not work? Is there a workaround I can use to cleanup the metrics?

Would appreciate the help! Thanks!

**Comment by zmstone** [comment]
HI @AndriyKhymera 
The path should be `/monitor`
Try send `DELETE .../api/v5/monitor`

**Pull request merged**
