### PR TITLE
Fix(coap): Make the username and password params to optional

### PR DESCRIPTION
**Pull request by HJianBo**
Fixes https://emqx.atlassian.net/browse/EMQX-10275

### <samp>🤖 Generated by Copilot at 0c8935e</samp>

This pull request improves the CoAP gateway functionality and refactors some common logic for gateways. It adds channel events, connection handling tests, and client information enrichment for the CoAP gateway. It also extracts a `random_clientid/1` function to the `emqx_gateway_utils` module and uses it for exproto channels.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [x] Changed lines covered in coverage report
- [x] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [x] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [x] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [x] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [x] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Review by qzhuyan — APPROVED** [review]

**Review by zhongwencool — APPROVED** [review]

**Review by qzhuyan — APPROVED** [review]

**Comment by id** [comment]
@Jerre1990 could you test with v5.1.2? Fresh docker images are available.

**Comment by Jerre1990** [comment]
@id latest on Docker Hub still refers to 5.1.1. I'll test as soon as I can pull the 5.1.2 image.

**Comment by id** [comment]
@Jerre1990 [emqx/emqx:latest](https://hub.docker.com/r/emqx/emqx/tags) is already updated, it points to 5.1.2.
emqx:latest should be updated soon https://github.com/docker-library/official-images/pull/15078

**Comment by Jerre1990** [comment]
@id I just tested with the latest 5.1.2 image and the issue still persists.

**Comment by HJianBo** [comment]
Hi  @Jerre1990  thanks for your feedback, 

> where the clientid query parameter is not extracted in Connectionless Mode. A random client ID is generated instead

Could you share the CoAP client request parameters and the CoAP gateway configurations? I'll have an investigation for this issue

**Comment by Jerre1990** [comment]
COAP gateway has default configuration:
- Connection Required: false
- Enable Statistics: true
- Publish QoS: coap
- Notification Message Type: qos
- Subscribe QoS: coap
- MountPoint: ((empty))
Default listener:
- Name: default
- Type: udp
- Bind: 5683
- Max Connections: 1024000
- Acceptors: -
No client authentication (also default).

The command I use to send the message (as described in the official documentation):
coap-client -m post -e "Hi, this is libcoap" "coap://0.0.0.0/ps/coap/test?retain=true&clientid=123id"
I have also tried another parameter name (as described in some older documentation):
coap-client -m post -e "Hi, this is libcoap" "coap://0.0.0.0/ps/coap/test?retain=true&**c**=123id"

I use _retain_ to be able to quickly check the client ID in the dashboard.

**Pull request merged**
