### PR TITLE
chore: update emqtt to 1.13.5

### PR DESCRIPTION
**Pull request by terry-xiaoyu**
Fixes https://emqx.atlassian.net/browse/EMQX-13415

Release version: v/e5.8.3

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Comment by zmstone** [comment]
quite some test cases failed.

**Review by zmstone — APPROVED** [review]

**Comment by terry-xiaoyu** [comment]
The mac build failed because of 404 error when trying to download quicer binaries. Waiting for fixes here: https://github.com/emqx/quic/pull/322

**Comment by terry-xiaoyu** [comment]
Waiting for this PR: https://github.com/emqx/emqx/pull/14283

**Comment by qzhuyan** [comment]
pls rebase on to latest release-58, we have quicer 0.1.9 there

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-5197)

**Pull request merged**
