### PR TITLE
fix(ws connection): fix peer_cert_as_username error when ws connect

### PR DESCRIPTION
**Pull request by Rory-Z**

### CODE REVIEW

**Comment by Rory-Z** [comment]
@tigercl Do we need to fix this problem in version 4.2?

**Comment by HJianBo** [comment]
Nice works @Rory-Z 

Some other important things:

1. we need some test cases to prevent the problem from happening again in the future.
2. we need to specify in the comments and emqx-docs, that this configuration is only valid when proxy-protocol is enabled

**Comment by Rory-Z** [comment]
Hi @HJianBo 

> we need some test cases to prevent the problem from happening again in the future.

I have no idea how to write a unit test for now, maybe can use jmeter to test it later.

> we need to specify in the comments and emqx-docs, that this configuration is only valid when proxy-protocol is enabled

Yep, I have added a comment

**Comment by HJianBo** [comment]
Maybe you can write a simple proxy-server to append the proxy-protocol to the ahead of TCP stream. In this way, we can test all the proxy-protcol related code.

**Comment by zmstone** [comment]
> e proxy-protcol related code.

I think @z8674558 is working on adding a new test suite with nginx added to verify http proxy headers.
After that, we can extend the test suite with cases to verify PROXY binary protocol

**Comment by Rory-Z** [comment]
> > e proxy-protcol related code.
> 
> I think @z8674558 is working on adding a new test suite with nginx added to verify http proxy headers.
> After that, we can extend the test suite with cases to verify PROXY binary protocol

Cool !

**Review by turtleDeng — APPROVED** [review]

**Review by HJianBo — APPROVED** [review]

**Pull request merged**
