### PR TITLE
fix(cluster link api): clientid is not required when updating

### PR DESCRIPTION
**Pull request by thalesmg**
Fixes https://emqx.atlassian.net/browse/EMQX-13183

Release version: e5.8.1

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [x] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Comment by zmstone** [comment]
will create fail without clientid ?

**Review by keynslug — APPROVED** [review]
> will create fail without clientid ?

Existing testcases and the bug report hint that it won't. I'm super surprised that updates didn't work the same.

**Comment by thalesmg** [comment]
> Existing testcases and the bug report hint that it won't. I'm super surprised that updates didn't work the same.

Indeed.  It seems like that the behavior of missing `required` properties in the schema is different when checking files and checking input in the HTTP API.  :thinking: 

> will create fail without clientid ?

The added test case covers that scenario.

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-4364)

**Pull request merged**
