### PR TITLE
Fix stomp gateway subscription_cnt is not updated timely and max_headers option is not working

### PR DESCRIPTION
**Pull request by HJianBo**
Fixes [EMQX-10152](https://emqx.atlassian.net/browse/EMQX-10152), [EMQX-10151](https://emqx.atlassian.net/browse/EMQX-10151)

### <samp>🤖 Generated by Copilot at 4065f08</samp>

This pull request adds a frame limit feature and improves the subscription metrics and the receipt frame handling for the `emqx_stomp` application. It also fixes a bug in the channel state update and adds test cases and helper functions for the STOMP gateway. It updates the version number to `0.1.1`.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [x] Changed lines covered in coverage report
- [x] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [x] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [x] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [x] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [x] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Review by zmstone — APPROVED** [review]
it sounds more reasonable to use `max_header_length` instead.
maybe add it as an alias.

**Comment by HJianBo** [comment]
Are you referring to renaming `max_headers` as `max_headers_lengths`? However, we actually have a configuration called `max_headers_length`, maybe we can rename `max_headers` as `max_headers_num`?

**Comment by yanzhiemq** [comment]
_

**Comment by yanzhiemq** [comment]
_

**Pull request merged**
