### PR TITLE
fix: deprecate unsupp quic TLS options

### PR DESCRIPTION
**Pull request by qzhuyan**
The idea was to remove unsupp QUIC TLS options to avoid confusion.
But removing fields can cause schema backward compatible issues, so we decide to mark them deprecated. 

Manually checked that the Swagger spec file has these fields deprecated.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [x] Changed lines covered in coverage report
- [x] Change log has been added to `changes/{ce,ee}/(feat|perf|fix)-<PR-id>.en.md` and `.zh.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [ ] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [x] Schema changes are backward compatible

### CODE REVIEW

**Comment by lafirest** [comment]
Q: Could we just ignore these and not mark them as deprecated? I don't familiar about QUIC, but I worry maybe these can be supported someday.

**Comment by lafirest** [comment]
Q: Could we just ignore these and not mark them as deprecated? I don't familiar about QUIC, but I worry maybe these can be supported someday.

**Comment by qzhuyan** [comment]
> Q: Could we just ignore these and not mark them as deprecated? I don't familiar about QUIC, but I worry maybe these can be supported someday.

I agree with you and that is exactly what I planned to do, add support in future releases but QA team doesn't like this idea they don't accept settings that takes no effect (updating doc stating it takes no effect on QUIC protocol is not accepted as well).

**Comment by qzhuyan** [comment]
and I assume we could remove the `deprecated` flag when I want to add them back.
Just want some input/review if it is possible without any other pitfalls.

**Review by thalesmg — APPROVED** [review]

**Review by savonarola — APPROVED** [review]

**Pull request merged**
