### PR TITLE
Use username replace id(issue#1737)

### PR DESCRIPTION
**Pull request by tigercl**
https://github.com/emqx/emqx/issues/1737

### CODE REVIEW

**Comment by tigercl** [comment]
https://github.com/emqx/emqx/issues/1737

**Comment by spring2maz** [comment]
client id has a limit of 23 bytes maximum, does username has such limit ?

**Comment by tigercl** [comment]
> client id has a limit of 23 bytes maximum, does username has such limit ?

We will check length of the client id after using username replace client id, and the server allow ClientID's that contain more than 23 encoded bytes actually, we limit it by 'max_clientid_len' in emqx.conf now.

**Comment by tigercl** [comment]
> Questings after reading mosquitto config document
@spring2maz Sorry for not replying in time, the plan you said is indeed more reasonable. I will discuss with @turtleDeng and decide how to achieve it later.

**Pull request merged**
