### PR TITLE
chore(update_appup): Improve `update_appup.escript`

### PR DESCRIPTION
**Pull request by thalesmg**
It is suggested to the review to read this PR by commit.

#### Make the script regex-aware

This change makes the `update_appup.escript` check whether the new
version of an application (the _current_ one) is already contained in
entries in the _new_ .appup file for that application if such .appup
file contains regexes.

NOTE: this does not cover the case in which we calculate the
difference between _old_ and _new_ appup entries, and those consist of
regexes.  In such case, we would need to check if one regex is
"contained" in the other, which is not currently supported by this
patch.

#### Do not use `load_module` instructions if `restart_application` is present

Since the appup instruction `restart_application` already loads all
modules of a given application, there is no need to introduce those
instructions if a restart is already present.

#### Do not force `.appup.src` render if contents are the same

To avoid losing comments and/or manual indentation in appup files that
are already up to date, we now check whether the contents have the
exact same terms as those we are about to write to an existint .appup
file.

#### Insert `load_module`s after `application:stop`, if present

If there is already any `application:stop(Application)` call in the
appup instructions, we prefer to add `load_module` instructions after
it, so we can be sure that the load is replaced safely.

#### Add expected versions check

For apps inside emqx umbrella, we try to bump only the patch part of
their version numbers, and use only 3-part version
numbers (`Major.Minor.Patch`).  With those assumptions, we may infer
all versions that need to be covered in a given upgrade, and check if
those are covered in regexes.

### CODE REVIEW

**Comment by thalesmg** [comment]
One example of regex case that is not covered here, where one regex would need to be "contained inside another":

The old `.appup.src` for `ehttpc-0.1.10` contains:

```erlang
  %% ...
  {<<"0.1.[8-9]">>,[{load_module,ehttpc,brutal_purge,soft_purge,[]}]},
  %% ...
```

The new one for `0.1.12` contains:

```erlang
%% ...
{<<"0\\.1\\.([8-9]|(1[0-1]))">>,
   [{load_module,ehttpc,brutal_purge,soft_purge,[]},
    {load_module,ehttpc_pool,brutal_purge,soft_purge,[]}]}
%% ...
``` 

By manual inspection, we see that the new regex "contains" the old
one.  But, in order to verify that, we'd need to somehow compute that
one contains the other, perhaps by generating version strings from one
and checking that the other matches.

Also, even the following simple changes cannot be checked to be the
same, because the regex was made more strict between versions, despite
being "the same":

```diff
- {<<"0.1.[0-7]">>,[{update,ehttpc,{advanced,[]}}]},
+ {<<"0\\.1\\.[0-7]">>,[{update,ehttpc,{advanced,[]}}]},
```

**Comment by zmstone** [comment]
Should this work?

* We assume the current version `4.3.{{ CURRENT }}` in .app is valid
  (with the help from the app vsn check CI job it's probably true)
* So the version can be read from .app, or even better if we get rid of 'VSN' in all .app.src files
* Enumerate all previous versions, from `4.3.0` to `4.3.{{ CURRENT - 1 }}`
  - For each enumerated version, find its position in the appup list, ensure newly changed beams are added

When release-handler (OTP code) generates relup instructions from .appup files,
it matches the baes version against the vsn (or regex) in the list from head to tail,
until it finds a match. Otherwise will fail

**Comment by thalesmg** [comment]
> Should this work?
> 
>     * We assume the current version `4.3.{{ CURRENT }}` in .app is valid
>       (with the help from the app vsn check CI job it's probably true)
> 
>     * So the version can be read from .app, or even better if we get rid of 'VSN' in all .app.src files,
>       then the CURRENT version is right there.
> 
>     * Enumerate all previous versions, from `4.3.0` to `4.3.{{ CURRENT - 1 }}`
>       
>       * For each enumerated version, find its position in the appup list, ensure newly changed beams are added
> 
> 
> When release-handler (OTP code) generates relup instructions from .appup files, it matches the baes version against the vsn (or regex) in the list from head to tail, until it finds a match. Otherwise will fail

That looks like a good procedure.  At first, I thought that I could assume that for all dependencies, but after I found out that some of them do not follow that convention, I kinda stopped pursuing that route.  Namely, both are _external_ dependencies: i) `ekka` has a 4-part version schema at one point (went from `0.8.1.4 -> 0.8.2`); ii) `gen_rpc` bumped the minor version number (went from `2.5.1 -> 2.7.0`).  Other dependencies were fine regarding that hypothesis, at least checking against 4.3.10.

On second thought now, we could still assume that we deal only patch version bumps and 3-part version schemas and use that to construct the set of versions that regexes should cover.  I believe that'll help in determining if one regex contains another, since the universe of versions will be finite and well defined, as a best-effort approach.  If that fails, we still report the (possibly) false positive.

I'll add that logic in a new commit.  Thanks!

**Comment by thalesmg** [comment]
Just as an extra clarification: the problem of checking whether one regex contains another only arises when we need to compute the difference between the expected and actual (new) .appup files, and that also only happens for external dependencies, since, for local ones, the files are just overwritten.

But the suggested approach should probably work for a few cases, like `ehttpc` (even if the regex itself changed).

**Comment by thalesmg** [comment]
With the current modifications, only 2 `.appup` files are written / reported to have missing actions:

##### `emqx.appup.src`

It adds `{load_module,emqx_app,brutal_purge,soft_purge,[]}` to both upgrade and downgrade instructions for `4.3.11`.  This instruction is indeed absent in the current file, and there are no `restart_application` instructions.

##### `ehttpc` (external)

```
       Missing changes: #{down =>
                              [{<<"0\\.1\\.0">>,
                                [{load_module,ehttpc_pool,brutal_purge,soft_purge,[]},
                                 {load_module,ehttpc,brutal_purge,soft_purge,[]}]},
                               {<<"0\\.1\\.[1-7]">>,
                                [{load_module,ehttpc_pool,brutal_purge,soft_purge,[]},
                                 {load_module,ehttpc,brutal_purge,soft_purge,[]}]}],
                          up =>
                              [{<<"0\\.1\\.[0-7]">>,
                                [{load_module,ehttpc_pool,brutal_purge,soft_purge,[]},
                                 {load_module,ehttpc,brutal_purge,soft_purge,[]}]}]}
```

Those instructions are indeed absent for `ehttpc.appup.src` in tag `0.1.12`.  There are `{update, ehttpc, {advanced, _}}` instructions in those versions.  While `ehttpc_pool` is indeed absent, maybe we should treat `{update, Mod, {advanced, _}}` in the same way as `restart_application`?

**Review by k32 — APPROVED** [review]

**Pull request merged**
