### PR TITLE
perf(mnesia): unify the copy types of all nodes

### PR DESCRIPTION
**Pull request by HJianBo**
Fixes:
https://github.com/emqx/emqx-rel/issues/624#issuecomment-753275340
https://github.com/emqx/emqx/issues/3993

### CODE REVIEW

**Comment by zmstone** [comment]
use macros for `ram_copies` and `disc_copies` to avoid changing only one place in future releases ?

**Comment by HJianBo** [comment]
I don't think this is necessary because the Copy Type can be different for different modules and different tables in the same module.

**Comment by zmstone** [comment]
> I don't think this is necessary because the Copy Type can be different for different modules and different tables in the same module.

I mean a local macro or a local function like `copy_type() -> disk_copy.` and use it in both of the `boot` clauses

**Review by zmstone — APPROVED** [review]

**Comment by HJianBo** [comment]
Hi @zmstone Pls check it again, I have push a new commit for resolving the elvis warnings.

**Review by zmstone — APPROVED** [review]

**Pull request merged**
