### PR TITLE
Fix typos in Docker README

### PR DESCRIPTION
**Pull request by lindhe**
I found a couple of typos when reading the README on Docker Hub. This change aims to improve the markdown and wording of that document.

To understand each change better, please inspect each commit individually. 👍

### CODE REVIEW

**Comment by lindhe** [comment]
I've amended all commits and force pushed to conform to the commit message gate.

**Review by ieQu1 — APPROVED** [review]

**Comment by ieQu1** [comment]
Hi @lindhe ,
Thanks for the PR! The CI complains about commit message format, the easiest way to fix it is to squash commits into a commit with `docs(docker): Fix typos` message.

**Comment by lindhe** [comment]
Oh, so the CI doesn't allow multiple commits?

Sure, I can squash it later today.

BTW, you know that you can have the GitHub PR [make a squash merge for you](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests), right? :)

**Comment by ieQu1** [comment]
> Oh, so the CI doesn't allow multiple commits?

It does, but the commit message format must follow a specific pattern: https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716
In this case I guess it's better to squash, since these changes are related semantically .

**Comment by lindhe** [comment]
Sorry, I missed the `:` 🤦‍♂️

**Comment by ieQu1** [comment]
Thanks, @lindhe !

**Pull request merged**
