### PR TITLE
fix(sessds): make streams ephemeral

### PR DESCRIPTION
**Pull request by keynslug**
Fixes [EMQX-11537](https://emqx.atlassian.net/browse/EMQX-11537).

Release version: v5.4

In other words, do not store them in mnesia. Keep only references to them as part of pubranges, a reference now is a hash of a stream. As long as we use streams themselves as their identities this must be safe.

Pros:
* Now that a set of streams always reflects a set of current subscriptions, unsubscribe just works.
* Less objects to manage in mnesia.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] ~~Added property-based tests for code which performs user input validation~~
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [ ] ~~Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket~~
- [x] Schema changes are backward compatible

### CODE REVIEW

**Comment by ieQu1** [comment]
How does it play with the concepts of fully replayed streams? We need to keep them to make stream scheduler work

**Comment by keynslug** [comment]
> We need to keep them to make stream scheduler work

Good point. There are already pubrange checkpoints which can probably hold `eos` in place of the last iterator, which supposedly would give the same effect. Anyway, this is worth a discussion.

**Review by ieQu1 — COMMENTED** [review]
I am afraid this will become a premature pessimization. In fact, I think we should move more data _away_ from ds_pubrange. I introduced this table as a quick hack to save the mapping from packet sequence numbers to the iterators, in case we need to replay messages. 

- I don't want `ds_pubrange` to become a God object, upon which the entire session logic relies. 
- `ds_pubrange` objects are the most frequently written ones (https://github.com/emqx/emqx/blob/master/apps/emqx/src/emqx_persistent_message_ds_replayer.erl#L276 - it's in the hot loop!; they can multiply uncontrollably if the client reads data in small chunks. 
- I think this object is the prime candidate for **removal** rather than extension

The number of stream objects, on the other hand, is well known since `emqx_ds` tries to minimize the number of streams.

**Review by ieQu1 — CHANGES_REQUESTED** [review]
I am afraid this will become a premature pessimization. In fact, I think we should move more data _away_ from ds_pubrange. I introduced this table as a quick hack to save the mapping from packet sequence numbers to the iterators, in case we need to replay messages. 

- I don't want `ds_pubrange` to become a God object, upon which the entire session logic relies. 
- `ds_pubrange` objects are the most frequently written ones (https://github.com/emqx/emqx/blob/master/apps/emqx/src/emqx_persistent_message_ds_replayer.erl#L276 - it's in the hot loop!; they can multiply uncontrollably if the client reads data in small chunks. 
- I think this object is the prime candidate for **removal** rather than extension

The number of stream objects, on the other hand, is well known since `emqx_ds` tries to minimize the number of streams.

**Comment by keynslug** [comment]
Very arguable points. But I'll just scrap this PR in favor of a more conservative approach. A couple of things for the context / history.

> I introduced this table as a quick hack

This table was introduced as part of #11958.

> they can multiply uncontrollably if the client reads data in small chunks

They definitely will, if: 1) streams are "live" and constantly but infrequently receive new writes, 2) client rarely acks publishes, or acks them in large batches.

**Pull request closed without merging**
