### PR TITLE
fix: default value for max_conn_rate etc should be set to infinity

### PR DESCRIPTION
**Pull request by kjellwinblad**
Before this PR the default value for the fields `max_conn_rate`, `messages_rate` and `bytes_rate` were not set. This is fixed by setting the default value to infinity. This breaks the corresponding dashboard fields (they can not be edited) so the dashboard also needs to be updated.

This change is according to @zmstone's suggestion in the JIRA ticket (https://emqx.atlassian.net/browse/EMQX-12514?focusedCommentId=41414)

Fixes:
https://emqx.atlassian.net/browse/EMQX-12514

Release version: v/e5.?

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [] Added property-based tests for code which performs user input validation
- [] Changed lines covered in coverage report
- [x] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [x] Schema changes are backward compatible

### CODE REVIEW

**Comment by kjellwinblad** [comment]
Created issue for the dashboard team to fix the fields after the change:

https://emqx.atlassian.net/browse/ED-1456

**Comment by zhongwencool** [comment]
```
Testing lib.emqx.emqx_ratelimiter_SUITE: *** FAILED test case 10 of 34 ***
%%% emqx_ratelimiter_SUITE ==> t_compatibility_for_node_short_paths: FAILED
%%% emqx_ratelimiter_SUITE ==> 
Failure/Error: ?assertMatch(# { rate := 20.0 }, Accessor ( bytes ))
  expected: = # { rate := 20.0 }
       got: #{rate => infinity,burst => 0.0}
      line: 781
```
ratelimiter SUITE is broken. need be fixed.

**Comment by kjellwinblad** [comment]
@ zhongwencool thanks, will fix the test case.

**Comment by kjellwinblad** [comment]
I added a commit to make the test pass.

This commit also removes the default value for `messages_rate` and `bytes_rate` as I'm not sure if they should have a default value.

Also, I'm not sure if my change to test case `emqx_ratelimiter_SUITE:t_no_limiter_for_listener` is correct. I think someone that understands the rate limiter system and our config needs to look at this to ensure that the changes are correct!

**Review by zmstone — APPROVED** [review]

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-2967)

**Pull request merged**
