### PR TITLE
ci(fix): skip flow when there are no changes

### PR DESCRIPTION
**Pull request by thalesmg**
```
Error when evaluating 'strategy' for job 'run_emqx_app_tests'. emqx/emqx/.github/workflows/run_emqx_app_tests.yaml@689347f60e5e2e5fc612aa0282c74c0eb26e8281 (Line: 65, Col: 9): Matrix must define at least one vector
```

Fixes <issue-or-jira-number>

Release version: v/e5.?

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Comment by thalesmg** [comment]
I wonder if this fix is really needed: the original [PR](https://github.com/emqx/emqx/pull/12778) ran with an empty matrix with the desired behavior.  :thinking:

**Comment by thalesmg** [comment]
Apparently a false alarm due to a [spurious workflow cancellation](https://github.com/emqx/emqx/actions/runs/8467542347/attempts/1?pr=12798) on another PR.

**Comment by thalesmg** [comment]
Even though it doesn't prevent the whole workflow run from completing successfully, it appears as a "failure" in the summary screen.

**Review by id — APPROVED** [review]

**Comment by emqxqa** [comment]
[Test Execution]()

**Pull request merged**
