### PR TITLE
chore: remove redundant health check call

### PR DESCRIPTION
**Pull request by thalesmg**
Since `emqx_resource_manager:channel_health_check` already does a base resource health check, the call was repeated.

Fixes [EMQX-12521](https://emqx.atlassian.net/browse/EMQX-12521)

Release version: v/e5.7.1

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

[EMQX-12521]: https://emqx.atlassian.net/browse/EMQX-12521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by zmstone** [comment]
according to thedescription in jira. Hc is done 3 times. This eliminates one, but there is another one left

**Comment by thalesmg** [comment]
> according to thedescription in jira. Hc is done 3 times. This eliminates one, but there is another one left

I think this change can be done safely, regardless of the ticket, so can be merged as is.

Also, as mentioned in the ticket, maybe it's not so bad to do 2 in a row if it's only for probing the config?  I'm not sure we can remove either of the remaining ones, due to different code paths reaching there.  @kjellwinblad , do you have any insights about that?

**Review by zmstone — APPROVED** [review]

**Comment by zmstone** [comment]
> > according to thedescription in jira. Hc is done 3 times. This eliminates one, but there is another one left
> 
> I think this change can be done safely, regardless of the ticket, so can be merged as is.
> 
> Also, as mentioned in the ticket, maybe it's not so bad to do 2 in a row if it's only for probing the config? I'm not sure we can remove either of the remaining ones, due to different code paths reaching there. @kjellwinblad , do you have any insights about that?

I agree to merge this one as it is.
However I think the third HC can be easily avoided too:
`emqx_resource_manager:add_channel/3` can be extended with a `/4` variation which does not immediately return `ok`, but for HC result, and call `/4` for `dryrun` resource. --- this is essentially what `emqx_bridge_v2:create_dry_run_helper` does anyway: add (which triggers an HC), then HC (and wait for result)

**Comment by thalesmg** [comment]
> I agree to merge this one as it is. However I think the third HC can be easily avoided too: `emqx_resource_manager:add_channel/3` can be extended with a `/4` variation which does not immediately return `ok`, but wait for HC result, and call `/4` for `dryrun` resource. --- this is essentially what `emqx_bridge_v2:create_dry_run_helper` does anyway: add (which triggers an HC), then HC (and wait for result)

:heavy_check_mark: 
https://github.com/emqx/emqx/pull/13220

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-2595)

**Pull request merged**
