### PR TITLE
feat(ipv6 probe): automatically probe whether it is IPv6

### PR DESCRIPTION
**Pull request by tigercl**
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## More information

### CODE REVIEW

**Comment by zmstone** [comment]
make it configurable ?

**Comment by tigercl** [comment]
> make it configurable ?

I'm not sure whether to make it configurable, the current behavior is similar to before. If you need to make it configurable, do you need to provide these three options: ipv4_only, ipv6_only, and ipv6_probe? Configurability is nothing more than to provide a mechanism to bypass this implementation, so while bypassing, it should provide the same capabilities as the original, namely ipv4_only and ipv6_only.

**Comment by zmstone** [comment]
`ipv6_probe` only works on EMQ's otp fork.
it is not compatible with upstream otp release, (`badarg` exception otherwise).
there are 3 ways forward.
1. make it configurable, default to false
2. add a compile flag
3. check at runtime.

there are two tests failing http-acl related

**Comment by qzhuyan** [comment]
> `ipv6_probe` only works on EMQ's otp fork.

Oops, I forget to mention that maybe we should consider the `ipv6 probe` to become application-wide configurable in OTP.

It doesn't make sense to be configurable in socket opts, or?

**Comment by zmstone** [comment]
> > `ipv6_probe` only works on EMQ's otp fork.
> 
> Oops, I forget to mention that maybe we should consider the `ipv6 probe` to become application-wide configurable in OTP.
> 
> It doesn't make sense to be configurable in socket opts, or?

it's a per remote peer (i.e. per-socket) config.
e.g. webhook may need it, but not http-auth.
so it has to be a per-socket config, socket opts seem to be the only place to put it.

**Comment by tigercl** [comment]
> `ipv6_probe` only works on EMQ's otp fork.
> it is not compatible with upstream otp release, (`badarg` exception otherwise).
> there are 3 ways forward.
> 
> 1. make it configurable, default to false
> 2. add a compile flag
> 3. check at runtime.
> 
> there are two tests failing http-acl related

I will add the corresponding configuration items first, but the original code will be retained. Does this mean that we need to test the two OTPs in the future?

**Review by terry-xiaoyu — APPROVED** [review]

**Comment by zmstone** [comment]
commit has been cherry-picked to:
https://github.com/emqx/emqx/pull/4693

**Pull request closed without merging**
