### PR TITLE
A better version of truncated logging.

### PR DESCRIPTION
**Pull request by johnfwhitmore**
I hope that this is based on the correct branch, and is a better solution to my issue with either too much or too little logging information.

To be honest I've struggled to get this version tested as whilst I had a build system  in place and working this fell to pieces today. Between the repos emqx/emqx  emqx/emqx-rel and emqx/emqx-packages I have no idea why when I build this code is not being built. 

Even the instructions given in the developers quickstart 'cd emqx && make rel' don't work. So this is untested code until I find some way to build and deploy it to a VM

### CODE REVIEW

**Comment by Gilbert-Wong** [comment]
Hi, @johnfwhitmore , ci failed. :)

**Comment by johnfwhitmore** [comment]
I Am well aware that CI Failed. I'm not an Erlang programmer so might have expected some comment more helpful then that. The main reason why CI probably failed is because I removed the "-spec" line for "format/1" in emqx_packet.erl and the function is now "format/2"

No mater what I do compiler ain't happy so I removed it. 

So have you any advice on the spec line of "format/2" or is "CI Failed" all you can tell me?

**Comment by johnfwhitmore** [comment]
Additionally very hard to test as your build system is - "not great"

**Comment by johnfwhitmore** [comment]
emqx/emqx-packages is building my code but when I install the resulting package it's not my code that's executing. Don't know where it's picking up emqx from.

The developer quickstart instructions mention "make rel" in emqx directory but that does nothing.

**Comment by Gilbert-Wong** [comment]
Sorry for your bad experience to test on our building system. We have been aware that our building system is not good enough and plan to improve it in emqx 3.2 release. And if you contribute code into emqx repo. You should run commands in .travis.yml first to ensure that your code can pass all checks.

**Comment by Gilbert-Wong** [comment]
emqx/emqx-packages are just build packages for target system. Generally, we build emqx directly in emqx-rel repo for developing and testing.

**Comment by johnfwhitmore** [comment]
Could you possibly tell me what the "-spec" line for format/2 should be?

I've removed that line from emqx_packet.erl and that's probably one of my CI issues

**Comment by Gilbert-Wong** [comment]
It is type spec, you can refer this link <http://erlang.org/doc/reference_manual/typespec.html>

**Comment by johnfwhitmore** [comment]
thanks for that. All I needed was the specify that the first parameter is an 'atom' 

I'll try check this change in.

**Comment by johnfwhitmore** [comment]
Sorry can't check in that one line change as I don't have access to my own computer with ssh keys.

**Comment by Gilbert-Wong** [comment]
Don't mind it. I'll help you fix this pr.

**Comment by johnfwhitmore** [comment]
If you could just change the -spec line in emqx_packets.erl to read:

-spec(format(atom, mqx_mqtt_types:packet()) -> iolist()).

It's just to add the "atom" as a first parameter.

At least that might get me past CI

**Comment by johnfwhitmore** [comment]
After that I've not tested the code as I can't get the build system to run it. That's an issue with the build system, which I'll have to resolve.

But if you could look at the changes and suggest whether they make sense and if the change I'm suggesting would be acceptable. It simply tries to log the entire message in "debug" and truncate the message in "info" mode.

**Comment by johnfwhitmore** [comment]
Got it building! Had remove "rm -rf emqx-rel/_rel" directory and rebuild. If I don't do that whilst it does compile my code it doesn't replace the executable with my.

I can now test out these changes. I'll let you know how I get on.

**Comment by johnfwhitmore** [comment]
That change is actually doing what I wanted! It works!

The one other change I might ask for is to change the logging level of the 'trace' call in emqx/src/emqx_tracer.erl. Line 70 which logs a message including the term "PUBLISH" should probably be debug and not info:

emqx_logger:debug(#{topic => Topic}, "PUBLISH to ~s: ~p", [Topic, Payload]).

**Comment by terry-xiaoyu** [comment]
@johnfwhitmore Hi, great thanks for your effort on this issue! 

I've reviewed your PR, but I believe it is not good to do logger-related thing in message_packet:format/2. We'd better do this in `emqx_logger_formatter` module, which is copied from [erlang-otp](https://www.google.com.tw/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiWq4Sl6tvhAhVEip4KHXRDDlIQFjAAegQIBhAC&url=https%3A%2F%2Fgithub.com%2Ferlang%2Fotp&usg=AOvVaw0yzRMbEtHIEMUk8Zkm4gma), and it is responsible for formatting the logger messages. 

Thanks to the OTP team, the `logger` already has relate configurations for this, they are `chars_limit`, `max_size`,  and `depth`. See http://erlang.org/doc/man/logger_formatter.html. So I added a `chars_limit` configuration in [another PR](https://github.com/emqx/emqx/pull/2459/files).

**Comment by johnfwhitmore** [comment]
Hi terry-xiaoyu,

Thanks for that I'll try that PR out here. But having looked at it I get the impression that your PR will truncate all messages, regardless of logging level. I'm not sure about that.

You'll know more about Erlang, MQTT and emqx then me, but let me try it out and get back to you.

**Comment by johnfwhitmore** [comment]
Just tried to add that configuration option to my emqx.conf file after checking out develop branch and emqx don't like it:

emacs _rel/emqx/etc/emqx.conf                                                                                                                                                                            ad_jwhitm1x@apollo:~/emqx/emqx-rel$ ./_rel/emqx/bin/emqx console                                                                                                                                                                             2019-04-19T02:54:08.224780-07:00 [error] You've tried to set log.chars_limit, but there is no setting with that name.
2019-04-19T02:54:08.224873-07:00 [error] Did you mean one of these?
2019-04-19T02:54:08.266522-07:00 [error] log.sasl
2019-04-19T02:54:08.266604-07:00 [error] log.primary_level
2019-04-19T02:54:08.266646-07:00 [error] node.process_limit
2019-04-19T02:54:08.321752-07:00 [error] Error generating configuration in phase transform_datatypes
2019-04-19T02:54:08.321852-07:00 [error] Conf file attempted to set unknown variable: log.chars_limit


if I do a git show in deps/emqx directory:

On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
ad_jwhitm1x@apollo:~/emqx/emqx-rel/deps/emqx$ git show
commit a8d2497480f6fdc1ae7ee79a052a4ee32a9b8458
Author: terry-xiaoyu <506895667@qq.com>
Date:   Fri Apr 19 16:33:48 2019 +0800

    Truncate logs that is too long

diff --git a/etc/emqx.conf b/etc/emqx.conf
index 610898b..5da71b1 100644
--- a/etc/emqx.conf
+++ b/etc/emqx.conf
@@ -368,6 +368,12 @@ log.dir = {{ platform_log_dir }}
 ## Default: emqx.log
 log.file = emqx.log

+## Limits the total number of characters printed for each log event.
+##
+## Value: Integer
+## Default: 1024
+log.chars_limit = 1024
+
 ## Maximum size of each log file.
 ##
 ## Value: Number

**Comment by terry-xiaoyu** [comment]
@johnfwhitmore 

Yes it will truncate all of the log messages.

For the problem, please check if `log.chars_limit` is there in your `emqx.conf`. You must have used the old configuration file and `emqx.schema`. Check out the `develop` branch of `emqx` project and then rebuild it.

**Comment by johnfwhitmore** [comment]
I do have that branch in emqx-rel/deps as my 'git show' command demonstrated.

I did a 'make' in emqx-rel and built fine but it's the configuration file I've changed:

emacs _rel/emqx/etc/emqx.conf

Perhaps that's the wrong file but it does appear to be the file read by emqx when it's started.

**Comment by johnfwhitmore** [comment]
Whilst the new configuration option does appear to be in the source directory file:
deps/emqx/etc/emqx.conf:log.chars_limit = 1024
The option is not built into the release configuration file:
grep -r chars_limit _rel/emqx/etc/emqx.conf

**Comment by terry-xiaoyu** [comment]
Use `find ./deps -name emqx -type d` to see if there is more than one emqx project in your `deps` dir. `erlang.mk` might use the wrong one if you have multiple emqx.

You could also remove the `_rel` and `rel` dir to make sure the files be replaced by the newest ones.

**Comment by johnfwhitmore** [comment]
Oops yes I'd changed the name of my version of the emqx project.

Thanks a million for your help

**Comment by johnfwhitmore** [comment]
Right your version certainly works, truncating messages even in 'debug' which works for me. I kinda like my output though ;)

2019-04-19 03:48:46.706 [info] UDP-E4B70F_publisher@10.1.200.100:45425 [Protocol] RECV PUBLISH(Q0, R0, D0, Topic=UDP_-E4B70/raw_data, PacketId=undefined, Payload=<<"[0.03258_0.62233_-0.79124_UDP-E4B70F_419">> ... 22662 Bytes)

Can see how many bytes of payload that the message contained 22662 Bytes.  You can see why we need to truncate them a bit ;)

So I'm happy with your version so next question is when does that develop branch end up in an official release?

It must be getting late over there so have a great weekend ;)  

Thanks again for all your help.

**Comment by terry-xiaoyu** [comment]
@johnfwhitmore 
The feature your PR provides is good but the code is not that clear, so I wrote my own one, sorry for that.

The building of packages for v3.1-rc3 is ongoing so you could try it tomorrow.

**Comment by johnfwhitmore** [comment]
Nothing to be sorry about, enjoyed having a look at Erlang it's different ;)

**Comment by terry-xiaoyu** [comment]
@johnfwhitmore I'd like to enlarge the default limit, see https://github.com/emqx/emqx/pull/2509. If you want a smaller value, change the config file as you wish.

**Pull request closed without merging**
