### PR TITLE
chore: update dashboard version

### PR DESCRIPTION
**Pull request by zmstone**

### CODE REVIEW

**Review by qzhuyan — DISMISSED** [review]

**Review by thalesmg — APPROVED** [review]
Nit: some changes seem to be lack of rebase?

**Comment by zmstone** [comment]
> Nit: some changes seem to be lack of rebase?

it's a rebase on top of your commit, not exactly linear, but almost ff

**Comment by zmstone** [comment]
> > Nit: some changes seem to be lack of rebase?
> 
> it's a rebase on top of your commit, not exactly linear, but almost ff

ah, ok, so now github forces linear commits.

**Review by thalesmg — APPROVED** [review]

**Comment by emqxqa** [comment]
[TestExecution]()

**Pull request merged**
