### PR TITLE
feat: disable HTTP rest api on replicant nodes

### PR DESCRIPTION
**Pull request by zhongwencool**
Disable`/api/v5/xxx` from replicant nodes.

### CODE REVIEW

**Comment by ieQu1** [comment]
I guess it's better to disable the listener altogether (don't listen on 18083)? If the dashboard listener is hidden behind the load balancer this approach will make it fail randomly.

**Comment by zhongwencool** [comment]
> I guess it's better to disable the listener altogether (don't listen on 18083)? If the dashboard listener is hidden behind the load balancer this approach will make it fail randomly.

we can't disable port, the `/status` is used by k8s to healthy status checking

**Review by zmstone — CHANGES_REQUESTED** [review]
Update CHANGES file to keep a record of this change.

Question: does this affect below functionalities:

* Metrics scraping
* Health check

**Comment by ieQu1** [comment]
> we can't disable port, the /status is used by k8s to healthy status checking

If the node cannot serve REST API then it shouldn't report status as healthy? For MQTT port healthcheck the load-balancer should try to open TCP connection to port 1883, I guess.

**Pull request closed without merging**
