### PR TITLE
Add test cases for emqx_reason_codes module

### PR DESCRIPTION
**Pull request by linjunjj**
Add test cases for emqx_reason_codes module

### CODE REVIEW

**Comment by Gilbert-Wong** [comment]
It is meaningless to add eunit test for functions which only has one term and whose returned value is certain value. I assumed this pull request should be closed. What do you think ? @terry-xiaoyu @tigercl

**Comment by Gilbert-Wong** [comment]
I would show you how to write better code for these test cases later, I'm going to have lunch :p

**Comment by Gilbert-Wong** [comment]
These codes show you how to write test cases to cover emqx_reason_codes https://github.com/emqx/emqx/ .

**Comment by linjunjj** [comment]
I learned, thank you

**Pull request closed without merging**
