### PR TITLE
chore: use configured matrix.profile when building elixir images

### PR DESCRIPTION
**Pull request by id**

### CODE REVIEW

**Comment by id** [comment]
@zmstone please take a look.

I'm not sure if the intention was to build `emqx` profile anyway, or we just forgot to update it to use value from matrix.

**Comment by thalesmg** [comment]
I believe the original intention was to build with Elixir only the CE profile for 2 distros, indeed.

**Comment by id** [comment]
In this case we need an 'if' here to not build elixir ce images when we are building ee.

**Comment by thalesmg** [comment]
> In this case we need an 'if' here to not build elixir ce images when we are building ee.

By default, all profiles are to be built [without Elixir](https://github.com/emqx/emqx/pull/9192/files#diff-553f243f22356b342cf7e0d9c072c33443ee797eef899cd70ee0d82c14403a29R107), and we only include the couple ones we want to use Elixir.

Unless something slipped through, that was the original intention with this matrix. :see_no_evil:

**Comment by id** [comment]
https://github.com/emqx/emqx/pull/9281

**Pull request closed without merging**
