### PR TITLE
refactor: rename `/users/{name}/change_pwd` to `/users/{name}/password`

### PR DESCRIPTION
**Pull request by sstrigler**
Fixes [EMQX-8373](https://emqx.atlassian.net/browse/EMQX-8373)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [x] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/` dir
- [x] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)
- [x] For internal contributor: there is a jira ticket to track this change
- [x] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [x] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section
- [ ] sync with dasboard team

### CODE REVIEW

**Review by lafirest — COMMENTED** [review]
Good job, do we need a change description?

**Comment by sstrigler** [comment]
> Good job, do we need a change description?

I think that I need to sync with the dashboard team at least. Where would a change description go (or what does it mean)?

**Comment by lafirest** [comment]
> > Good job, do we need a change description?
> 
> I think that I need to sync with the dashboard team at least. Where would a change description go (or what does it mean)?

I mean this one `Change log has been added to changes/ dir`, but the modification is small so that this may not be needed

**Comment by sstrigler** [comment]
> 



> > > Good job, do we need a change description?
> > 
> > 
> > I think that I need to sync with the dashboard team at least. Where would a change description go (or what does it mean)?
> 
> I mean this one `Change log has been added to changes/ dir`, but the modification is small so that this may not be needed

Oh, of course. I'll add one once it's clear it's not going into 5.0.12. Which is basically clear now. But I've also posted some thoughts on slack, there might be more we want to do.

**Review by lafirest — APPROVED** [review]

**Pull request closed without merging**
