### PR TITLE
refactor(client_attr): allow more than one initial extraction

### PR DESCRIPTION
**Pull request by zmstone**
Fixes [EMQX-11882](https://emqx.atlassian.net/browse/EMQX-11882)

Release version: v/e5.7.0

## Summary

A follow up change for this comment: https://github.com/emqx/emqx/pull/12750#discussion_r1538921794

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [x] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [x] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [~] Schema changes are backward compatible (the change base is not released yet)

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

[EMQX-11882]: https://emqx.atlassian.net/browse/EMQX-11882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by zmstone** [comment]
will change to only use variform, drop regexp.

**Comment by savonarola** [comment]
Sorry if stupid question, but what is `variform`? 😅

**Comment by zmstone** [comment]
> Sorry if stupid question, but what is `variform`? 😅

It's not a word, it's a term created in this PR: https://github.com/emqx/emqx/pull/12851

**Comment by zmstone** [comment]
moved to this: https://github.com/emqx/emqx/pull/12872

**Pull request closed without merging**
