### PR TITLE
chore(charts): fix typos

### PR DESCRIPTION
**Pull request by Tautcius**
Typo in if statement that prevented creation of Certificate resource.

### CODE REVIEW

**Review by Rory-Z — APPROVED** [review]

**Comment by HJianBo** [comment]
Thanks for your contribution @Tautcius 
Could you pls amend the commit for fixing the `run_gintlint` CI failure? i.e: `chore(charts): fix typos`

**Comment by Tautcius** [comment]
> 

just updated commit name, please check. Please let me know if helped.

**Review by qzhuyan — DISMISSED** [review]

**Review by Rory-Z — DISMISSED** [review]

**Review by HJianBo — APPROVED** [review]

**Comment by HJianBo** [comment]
> 
> 
> just updated commit name, please check. Please let me know if helped.

In fact, I was talking about your git commit, not the title of the PR. I have force updated your commit log so that you can check it

**Comment by mindrunner** [comment]
That one was on me. Was about to fix that. Happy to see someone already did. Thanks @Tautcius

**Pull request merged**
