### PR TITLE
fix(helm): Remove ingress.mgmt.* parameters

### PR DESCRIPTION
**Pull request by urechi**
#8797

### CODE REVIEW

**Review by qzhuyan — APPROVED** [review]

**Comment by qzhuyan** [comment]
LGTM, thanks for the PR

**Comment by qzhuyan** [comment]
@urechi , gitlint check is failed, could you amend your commit message?

fix(helm): Remove ingress.mgmt.* parameters

**Review by qzhuyan — APPROVED** [review]

**Comment by qzhuyan** [comment]
@zmstone  Ready to merge.

**Comment by id** [comment]
@urechi could you please rebase on latest master?

**Pull request closed without merging**
