### PR TITLE
Truncating Logged MQTT messages in log files

### PR DESCRIPTION
**Pull request by johnfwhitmore**
This is a simple, if crude fix to the issue I created on the subject:

https://github.com/emqx/emqx/issues/2442

Whilst this is crude it does work. At present it simply truncates the MQTT messages with a hard coded magic number, in this case 40 characters. This should probably be a configuration option, or set to zero by default if there is to be no truncation of messages.

At preset the messages are blindly truncated where as an indication that the message was truncated would be nice to have, some thing like:
<<1,2,3,4,5,6,7,8,9,10 ... 1230 Bytes>>

It would also make sense if there was an additional logging function which would log the messages in truncated form in a log level of info or when is debug mode logs the entire message in its entirety.

I might look into additions to this feature and add more commits to this branch.

### CODE REVIEW

**Comment by Gilbert-Wong** [comment]
Hi, @johnfwhitmore , Thanks for your contribution, but you need to rebase your branch to develop branch of emqx and then pull request again.

**Comment by johnfwhitmore** [comment]
To the develop "branch" or "develop-3.2"?

**Comment by Gilbert-Wong** [comment]
Hi, @johnfwhitmore, after discussion this morning, we determine not to merge this pull request because our team leader think it is not necessary to truncate logged messages when log level is debug. Anyway, really appreciate your work and thanks for your contribution. Personally, I think it could be merged.

**Comment by Gilbert-Wong** [comment]
If you want to contribute code to emqx , you should fork from develop branch of emqx and then pull request here.

**Comment by johnfwhitmore** [comment]
I agree! That was in my issue that messages should not be truncated when the log level is debug but you go from having streams of logging messages in Debug to having Zero logging information when the log level goes to "info" That's unusable. In the info log level you should have some indication in the log files of what is happening, a summary of the messages being received rather then the full potentially 14K message!

**Comment by Gilbert-Wong** [comment]
We'll take the issue you said into account. Thanks for your feedback.

**Comment by johnfwhitmore** [comment]
The code I added was just so that I could try this out with some level of logging which is not trying to write a 14K message to a log file. 

So to go over this again there should be a new log function which implements the logic

truncate(log_level, Payload)
    if log_level == debug -> Payload
       log_level == info -> binary.part(Payload, 0, 40)

The problem is that you have to pass the log level around

**Comment by johnfwhitmore** [comment]
The real problem here is that you either set logging to debug and get too much logging info or you set the log level to 'info' and get nothing.

The log level should be used to adjust the amount of information being logged. In 'debug' the incoming message gets logged a number of times, as it passes through the stack. That's fine and it gives a detailed view of what emqx is doing but 'info' should just give a summary of what's being received.

I'll redo this by adding more 'info' log calls and truncate those. But the function in emqx_packet.erl does not have any idea of the calling log level!

**Pull request closed without merging**
