### PR TITLE
fix: add clusterDomain in values

### PR DESCRIPTION
**Pull request by Diaoul**
It's not uncommon to use another clusterDomain in Kubernetes.
With this new config value, it's possible to avoid manually overriding some environment variables.

### CODE REVIEW

**Comment by Diaoul** [comment]
Tested on my cluster with [my fork](https://github.com/Diaoul/helm-charts/tree/main/charts/emqx) and it works as intended.

**Review by qzhuyan — APPROVED** [review]
Good idea!

**Review by Rory-Z — DISMISSED** [review]

**Comment by Rory-Z** [comment]
Hi @Diaoul, Could you please sync this change to `deploy/charts/emqx-enterprise`

**Comment by zmstone** [comment]
Hi @Diaoul 
could you please rebase your branch on `release-50` ?
usually `master` is fine, but the next release will be cut from `release-50`

**Comment by Diaoul** [comment]
Thanks for your patience.
We should be good now :pray:

**Comment by Diaoul** [comment]
What is the next step here? Am I expected to fix the tests? (unsure why they broke)

**Review by Rory-Z — APPROVED** [review]

**Review by HJianBo — APPROVED** [review]

**Comment by zmstone** [comment]
Sorry @Diaoul 
this missed the release v5.0.16
will be included in v5.0.17 in about two weeks.

**Pull request merged**
