### PR TITLE
fixed shared subscription callback configuration data structure error

### PR DESCRIPTION
**Pull request by tyt0223**

### CODE REVIEW

**Comment by zmstone** [comment]
hi @tyt0223 could you elaborate on what issue this PR solves?

**Comment by tyt0223** [comment]
the function `publish_event_msg` of the module 'emqx_event_message' will report an error because the payload contains data with 'value' as a tuple when the share subscription message is published.

**Comment by tyt0223** [comment]
> hi @tyt0223 could you elaborate on what issue this PR solves?

the function publish_event_msg of the module 'emqx_event_message' will report an error because the payload contains data with 'value' as a tuple when the share subscription message is published.
error message is as follows:
Failed to execute {emqx_event_message,on_message_acked,[]}: {error,{invalid_ejson,{<0.2407.0>,#Ref<0.4001000432.4268752897.254554>}},[{jiffy,encode,2,[{file,"jiffy.erl"},{line,99}]},{emqx_json,encode,1,[{file,"emqx_json.erl"},{line,58}]},{emqx_event_message,publish_event_msg,2,[{file,"emqx_event_message.erl"},{line,265}]},{emqx_event_message,on_message_acked,2,[{file,"emqx_event_message.erl"},{line,183}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,205}]},{emqx_hooks,do_run,2,[{file,"emqx_hooks.erl"},{line,171}]},{emqx_channel,handle_in,2,[{file,"emqx_channel.erl"},{line,652}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,672}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,369}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,375}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,333}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}]} mfa: emqx_hooks:safe_execute/2 line: 209

**Comment by zmstone** [comment]
Thank you for the info.

`shared_dispatch_ack` is very much internal.
I believe the better way to fix it is to drop this header in the event messages (`on_message_acked` and such).

**Pull request closed without merging**
