### PR TITLE
style(api): imports removed

### PR DESCRIPTION
**Pull request by sh3d2**
Fixes <issue-number>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## More information

### CODE REVIEW

**Comment by sh3d2** [comment]
@zmstone a little housekeeping effort ;)

**Comment by zmstone** [comment]
> @zmstone a little housekeeping effort ;)

This is great.
Would be better if it's sent in another PR though.
easier to review.

**Comment by zmstone** [comment]
> > @zmstone a little housekeeping effort ;)
> 
> This is great.
> Would be better if it's sent in another PR though.
> easier to review.

oh, sorry, I thought I was commenting in the other PR.

**Review by zmstone — APPROVED** [review]

**Comment by zmstone** [comment]
will merge tomorrow if CI is green.

**Review by HJianBo — APPROVED** [review]

**Review by Rory-Z — APPROVED** [review]

**Pull request merged**
