### PR TITLE
fix(plugins): ensure plugin apps are restarted when restarting `emqx_plugins`

### PR DESCRIPTION
**Pull request by thalesmg**
Fixes https://emqx.atlassian.net/browse/EMQX-12628 

Fixes https://github.com/emqx/emqx/issues/13378

Release version: v/e5.7.2

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [x] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Comment by thalesmg** [comment]
I didn't add `ensure_stopped` to the more appropriate `application:stop/1` callback because that leads to a dead lock, as the code eventually calls [`application_controller`](https://github.com/emqx/emqx/blob/532f04da9d5628ad4e041329c8124b80e556b2f7/apps/emqx_plugins/src/emqx_plugins.erl#L851).  `application:prep_stop/1` suffers from the same problem.

An alternative could be to have a callback for `emqx_machine_boot` that is called before actually stopping the application, without being inside an `application_controller` call.

**Comment by zmstone** [comment]
> An alternative could be to have a callback for `emqx_machine_boot` that is called before actually stopping the application, without being inside an `application_controller` call.

I think this is a good idea.
Plugins can be stopped in `emqx_machin_boot:stop_apps/0` (before stopping native apps).

**Comment by thalesmg** [comment]
I didn't add `ensure_stopped` to the more appropriate `application:stop/1` callback because that leads to a dead lock, as the code eventually calls [`application_controller`](https://github.com/emqx/emqx/blob/532f04da9d5628ad4e041329c8124b80e556b2f7/apps/emqx_plugins/src/emqx_plugins.erl#L851).  `application:prep_stop/1` suffers from the same problem.

An alternative could be to have a callback for `emqx_machine_boot` that is called before actually stopping the application, without being inside an `application_controller` call.

> > An alternative could be to have a callback for `emqx_machine_boot` that is called before actually stopping the application, without being inside an `application_controller` call.
> 
> I think this is a good idea. Plugins can be stopped in `emqx_machin_boot:stop_apps/0` (before stopping native apps).

:checkered_flag:

**Review by zmstone — APPROVED** [review]

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-2890)

**Pull request merged**
