### PR TITLE
chore: make spellcheck happy

### PR DESCRIPTION
**Pull request by HJianBo**

### CODE REVIEW

**Comment by ieQu1** [comment]
Thank you!

**Review by ieQu1 — DISMISSED** [review]

**Comment by ieQu1** [comment]
After running `scripts/spellcheck` I found a bug in the script that interprets some parts of the code block as HTML tags. I will try make a quick fix.

**Comment by ieQu1** [comment]
I picked up your changes here: https://github.com/emqx/emqx/pull/7712/files

**Comment by HJianBo** [comment]
Ok, let me merge that as soon as possible

**Pull request closed without merging**
