### PR TITLE
chore(docker): add option to stop local testing containers (v5.0)

### PR DESCRIPTION
**Pull request by thalesmg**

### CODE REVIEW

**Review by id — DISMISSED** [review]

**Comment by thalesmg** [comment]
added ignore to shellcheck complaint

**Review by id — APPROVED** [review]

**Comment by thalesmg** [comment]
@id  strange, GH hasn't accepted your approval as enough for merging, even though you're the code owner for [`/scripts/`](https://github.com/emqx/emqx/blob/7985cd3536bfea71261f700fa00c1abe29b2e058/.github/CODEOWNERS#L37) :thinking:

**Comment by thalesmg** [comment]
@id I think the default case for the code owners file (Stone) should be the first declaration in the file, as [the last matching pattern takes the most precedence](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file).

**Comment by id** [comment]
https://github.com/emqx/emqx/pull/9665

**Comment by id** [comment]
@thalesmg rebase?

**Review by id — APPROVED** [review]

**Review by id — APPROVED** [review]

**Pull request merged**
