### PR TITLE
fix(authn): body type is wrong

### PR DESCRIPTION
**Pull request by tigercl**

### CODE REVIEW

**Comment by zmstone** [comment]
add a test?

**Comment by zhongwencool** [comment]
the raw config's key always is binary.
the config's key is always atom.
-----
you can't change this by coverter:
https://github.com/emqx/emqx/blob/master/apps/emqx/src/emqx_config.erl#L290
you can use atom instead.

**Comment by savonarola** [comment]
A related PR: https://github.com/emqx/emqx/pull/6302

But I am not sure that I can figure out the case solved by the fix.

**Comment by tigercl** [comment]
> the raw config's key always is binary. the config's key is always atom.
> 
> you can't change this by coverter: https://github.com/emqx/emqx/blob/master/apps/emqx/src/emqx_config.erl#L290 you can use atom instead.

We should be able to confirm that the converter will not affect other configurations now.


> A related PR: #6302
> 
> But I am not sure that I can figure out the case solved by the fix.

**Comment by tigercl** [comment]
> A related PR: #6302
> 
> But I am not sure that I can figure out the case solved by the fix.

It looks like this problem has been fixed by https://github.com/emqx/emqx/pull/6302, I will close this PR.

**Pull request closed without merging**
