### PR TITLE
fix content type returned by Stomp

### PR DESCRIPTION
**Pull request by cisiqo**
Fixes [https://github.com/emqx/emqx/issues/11369](https://github.com/emqx/emqx/issues/11369)

### <samp>🤖 Generated by Copilot at ea03dcf</samp>

This pull request improves the STOMP gateway by fixing a bug that caused duplicate headers, simplifying the version negotiation logic, and removing an unnecessary header for `MESSAGE` commands.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

**Comment by HJianBo** [comment]
Thanks for your  PR @cisiqo  Could you help to fix the CI failures? So that we can approve and merge it.

**Comment by cisiqo** [comment]
I have fixed the commit info. @HJianBo

**Comment by zmstone** [comment]
Hi @cisiqo 
Thank you for the PR and sorry for the late reply.
We do not support squash-merge in PR merge button.
could you help to squash your commits ?

**Comment by id** [comment]
@cisiqo could you check if this failure https://github.com/emqx/emqx/actions/runs/6730975993/job/18295406036?pr=11859#step:6:172 is related to your changes?

```
%%% emqx_stomp_SUITE ==> t_subscribe: FAILED
%%% emqx_stomp_SUITE ==> {{badmatch,{error,timeout}},
 [{emqx_stomp_SUITE,'-t_subscribe/1-fun-11-',1,
                    [{file,"/__w/emqx/emqx/apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl"},
                     {line,228}]},
  {emqx_stomp_SUITE,with_connection,1,
                    [{file,"/__w/emqx/emqx/apps/emqx_gateway_stomp/test/emqx_stomp_SUITE.erl"},
                     {line,1052}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1782}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1291}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1223}]}]}
```

**Review by HJianBo — APPROVED** [review]
LGTM, thanks for everyone

**Pull request merged**
