### PR TITLE
Merge main v4.3 into v4.4

### PR DESCRIPTION
**Pull request by HJianBo**

### CODE REVIEW

**Comment by HJianBo** [comment]
Do we need to remove Elvis Check for v4.4? @savonarola @zmstone 
(see: https://github.com/emqx/emqx/pull/7066

**Comment by savonarola** [comment]
> Do we need to remove Elvis Check for v4.4? @savonarola @zmstone 
> (see: https://github.com/emqx/emqx/pull/7066

I think yes, but let's wait for @zmstone :)

**Comment by zmstone** [comment]
> > Do we need to remove Elvis Check for v4.4? @savonarola @zmstone
> > (see: #7066
> 
> I think yes, but let's wait for @zmstone :)

Yes. Remove it.
4.4 now enters the same status like 4.4. I.e Maintenance mode

**Comment by zmstone** [comment]
flaky test case, jira has been created to follow up.  EMQX-3475

**Review by zmstone — APPROVED** [review]

**Pull request merged**
