### PR TITLE
fix(logs): set password field sensitive for connectors

### PR DESCRIPTION
**Pull request by savonarola**

### CODE REVIEW

**Comment by lafirest** [comment]
I have just posted the [`redact`](https://github.com/emqx/emqx/pull/9593) from 4.3 to master, I think we may have duplicated work

**Comment by zmstone** [comment]
> I have just ported the [`redact`](https://github.com/emqx/emqx/pull/9593) from 4.3 to master, I think we may have duplicated work

irrelevant

**Comment by zmstone** [comment]
> > I have just ported the [`redact`](https://github.com/emqx/emqx/pull/9593) from 4.3 to master, I think we may have duplicated work
> 
> irrelevant

related: https://github.com/emqx/emqx/pull/9608

**Comment by zmstone** [comment]
included in https://github.com/emqx/emqx/pull/9608

**Pull request closed without merging**
