### PR TITLE
fix emqx_vm allocator info otp 23 compatibility

### LINKED ISSUE #3832: EMQX  2.4.3 dashboard : request failed with status code 500 error
**Environment**:

- EMQ X version 4.2.3
- Hardware configuration (e.g. `lscpu`):
- OS 
 System Version: macOS 10.15.5 (19F101)
      Kernel Version: Darwin 19.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: OKC1234’s MacBook Pro
      User Name: OKC1234 (okc1234)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7 days 1:50
- Kernel : Darwin OKC1234s-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_6
- Erlang/OTP version (in case you build emqx from source code): 
  Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]
- Others:

**What happened and what you expected to happen**:
    I took the git hub source of emqx-rel. built it locally on my machine and started emqx broker. broker started successfully
. But when i go to dashbaord keep getting  request failed with status code 500 error.
1. not able to view the metrics
2. not able to add rule
3. not able to view plugins

**How to reproduce it (as minimally and precisely as possible)**:
  in macos 

  1. git clone https://github.com/emqx/emqx-rel
  2. install erlang version 23
  3. go to folder emqx-rel
  4. git checkout master
  5. export EMQX_DEPS_DEFAULT_VSN=v4.2.3
  6. make
  7 on successful build 
  8. Go to /Users/okc1234/emqx-rel/_build/emqx/rel
  9. run bin/emqx start
 10. Go to http://localhost:18083/#/
 11. try to navigate through monitor clients etc

you will see the error as [attached](url)
image

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by zmstone**
Fixes #3832

recon has the fix in this commit:
https://github.com/ferd/recon/commit/58071e37599a8154a3a32dc282209357cdbafdd9

### CODE REVIEW

**Comment by zmstone** [comment]
By the look of it, all the memory usage calculation code in emqx_vm can be replaced with recon_alloc.
Should be fixed in another PR (low priority though)

**Comment by HJianBo** [comment]
Agree, but the `emqx_vm` module and its some exported functions should be kept.

**Review by HJianBo — APPROVED** [review]

**Comment by jovdipp** [comment]
I'm not sure, this is the right approach. As I have been tracing the usage of the Allocators which in OTP 23 does not include 'blocks_size'. 
There are references to 'blocks_size' as a param from container_size, which leads to :
element(Pos, lists:keyfind(Container, 1, PoolProps));
( that would throw an exception ).

**Comment by jovdipp** [comment]
Perhaps as @zmstone mentioned all memory usage code in emqx_vm should be replaced or call the recon_alloc, so as not to diverge from other related memory functions inside recon_alloc which have/will be updated along side version upgrades.

**Comment by jovdipp** [comment]
> I'm not sure, this is the right approach. As I have been tracing the usage of the Allocators which in OTP 23 does not include 'blocks_size'.
> There are references to 'blocks_size' as a param from container_size, which leads to :
> element(Pos, lists:keyfind(Container, 1, PoolProps));
> ( that would throw an exception ).

I have double checked, seems I traced on version 2.5.0 instead of 2.5.1.. 'blocks_size' is in the props but not in the expected tuple format but rather as in Int.

**Comment by zmstone** [comment]
@jovdipp I’m not quite following. 
you confirm that the issue was in 2.5.0 and fixed in 2.5.1 ?
Or do you mean there is still issue with 2.5.1?

**Comment by jovdipp** [comment]
> @jovdipp I’m not quite following.
> you confirm that the issue was in 2.5.0 and fixed in 2.5.1 ?
> Or do you mean there is still issue with 2.5.1?

Still an issue.

**Comment by zmstone** [comment]
@jovdipp it seems your comment about `blocks_size` being a tuple of one Int in it was not true?
see print outs from my test:
```
   {mbcs,
       [{blocks,0,0,5},
        {blocks_size,0,0,10904},
        {foreign_blocks,[]},
        {raw_blocks,[{temp_alloc,[{count,0,0,5},{size,0,0,10904}]}]},
        {carriers,1,1,1},
        {mseg_alloc_carriers,0},
        {sys_alloc_carriers,1},
        {carriers_size,131072,131072,131072},
        {mseg_alloc_carriers_size,0},
        {sys_alloc_carriers_size,131072}]},
```

**Comment by jovdipp** [comment]
> @jovdipp it seems your comment about `blocks_size` being a tuple of one Int in it was not true?
> see print outs from my test:
> 
> ```
>    {mbcs,
>        [{blocks,0,0,5},
>         {blocks_size,0,0,10904},
>         {foreign_blocks,[]},
>         {raw_blocks,[{temp_alloc,[{count,0,0,5},{size,0,0,10904}]}]},
>         {carriers,1,1,1},
>         {mseg_alloc_carriers,0},
>         {sys_alloc_carriers,1},
>         {carriers_size,131072,131072,131072},
>         {mseg_alloc_carriers_size,0},
>         {sys_alloc_carriers_size,131072}]},
> ```

I saw this in recon 👍 
 {mbcs_pool,[{blocks,0},
               {blocks_size,0},
               {foreign_blocks,[]},
               {raw_blocks,[]},
               {carriers,0},
               {carriers_size,0},
               {entrance_removed,0,0},
               {skip_race,0,0}, 
               {skip_homecoming,0,0},
               {skip_not_pooled,0,0},
               {skip_busy,0,0},
               {skip_size,0,0},
               {fetch,0,0},
               {fail,0,0},
               {fail_pend_dealloc,0,0},
               {fail_shared,0,0},
               {fail_pooled,0,0}]},

**Comment by jovdipp** [comment]
> > @jovdipp it seems your comment about `blocks_size` being a tuple of one Int in it was not true?
> > see print outs from my test:
> > ```
> >    {mbcs,
> >        [{blocks,0,0,5},
> >         {blocks_size,0,0,10904},
> >         {foreign_blocks,[]},
> >         {raw_blocks,[{temp_alloc,[{count,0,0,5},{size,0,0,10904}]}]},
> >         {carriers,1,1,1},
> >         {mseg_alloc_carriers,0},
> >         {sys_alloc_carriers,1},
> >         {carriers_size,131072,131072,131072},
> >         {mseg_alloc_carriers_size,0},
> >         {sys_alloc_carriers_size,131072}]},
> > ```
> 
> I saw this in recon 👍
> {mbcs_pool,[{blocks,0},
> {blocks_size,0},
> {foreign_blocks,[]},
> {raw_blocks,[]},
> {carriers,0},
> {carriers_size,0},
> {entrance_removed,0,0},
> {skip_race,0,0},
> {skip_homecoming,0,0},
> {skip_not_pooled,0,0},
> {skip_busy,0,0},
> {skip_size,0,0},
> {fetch,0,0},
> {fail,0,0},
> {fail_pend_dealloc,0,0},
> {fail_shared,0,0},
> {fail_pooled,0,0}]},

mbcs_pool is what I was focusing on, due to 👍 

`container_value(Props, Pos, mbcs = Type, Container) when is_integer(Pos)->
    Pool = case proplists:get_value(mbcs_pool, Props) of
               PoolProps when PoolProps =/= undefined ->
                   element(Pos, lists:keyfind(Container, 1, PoolProps));
               _ ->
                   0
           end,
    TypeProps = proplists:get_value(Type, Props),
    Pool + element(Pos, lists:keyfind(Container, 1, TypeProps));`

**Comment by zmstone** [comment]
As discussed with @jovdipp , `mbcs_pool` is fine, because `Pos` in the `container_value` call is `2` --- which works fine with `{blocks_size, Int}`

**Pull request merged**
